# Generated by Django 5.0.7 on 2024-08-05 12:21

import django.db.models.deletion
import videojobs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AudioSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profanity', models.BooleanField(blank=True, default=False)),
                ('xenophobia', models.BooleanField(blank=True, default=False)),
                ('own_words', models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.CreateModel(
            name='VideoSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bad_habits', models.BooleanField(blank=True, default=False)),
                ('blood', models.BooleanField(blank=True, default=False)),
                ('nudity', models.BooleanField(blank=True, default=False)),
            ],
        ),
        migrations.CreateModel(
            name='VideoJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videofile', models.FileField(upload_to=videojobs.models.get_uploaded_videofile_path)),
                ('title', models.CharField(max_length=255)),
                ('size', models.FloatField(blank=True)),
                ('language', models.CharField(choices=[('EN', 'English'), ('RU', 'Russian')], max_length=2)),
                ('status', models.CharField(blank=True, choices=[('P', 'Processing'), ('S', 'Succeeded'), ('F', 'Failed')], default='P', max_length=1)),
                ('audio_setting', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='videojobs.audiosetting')),
                ('video_setting', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='videojobs.videosetting')),
            ],
        ),
    ]
