# Generated by Django 5.0.8 on 2024-08-10 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videojobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiosetting',
            name='own_words',
            field=models.TextField(blank=True, default='', help_text='Comma separated string of words'),
        ),
    ]
