# Generated by Django 5.0.7 on 2024-08-06 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videojobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videojob',
            name='input_videofile',
            field=models.CharField(max_length=100),
        ),
    ]
