# Generated by Django 5.0.8 on 2024-08-11 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videojobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videojob',
            name='audio_setting',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='videojobs.audiosetting'),
        ),
        migrations.AlterField(
            model_name='videojob',
            name='status',
            field=models.CharField(blank=True, choices=[('P', 'Processing'), ('S', 'Completed'), ('F', 'Failed')], default='P', max_length=1),
        ),
        migrations.AlterField(
            model_name='videojob',
            name='video_setting',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='videojobs.videosetting'),
        ),
    ]
