# Generated by Django 5.0.8 on 2024-08-10 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videojobs', '0002_alter_audiosetting_own_words'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiosetting',
            name='own_words',
            field=models.TextField(blank=True, help_text='Comma separated string of words'),
        ),
    ]
