# Generated by Django 5.0.7 on 2024-08-06 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videojobs', '0002_alter_videojob_input_videofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videojob',
            name='audio_setting',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='videojobs.audiosetting'),
        ),
        migrations.AlterField(
            model_name='videojob',
            name='video_setting',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='videojobs.videosetting'),
        ),
    ]
