# Generated by Django 5.0.8 on 2024-08-12 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videojobs', '0002_alter_videojob_audio_setting_alter_videojob_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videojob',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
