# Generated by Django 5.0.8 on 2024-08-13 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videojobs', '0003_videojob_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videojob',
            name='text',
        ),
    ]
