# Generated by Django 5.0.8 on 2024-08-13 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videojobs', '0004_remove_videojob_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videojob',
            name='language',
            field=models.CharField(choices=[('ru', 'English'), ('en', 'Russian')], max_length=2),
        ),
    ]
