# Generated by Django 5.0.7 on 2024-08-07 12:56

from django.db import migrations, models

import videojobs.models


class Migration(migrations.Migration):

    dependencies = [
        ('videojobs', '0004_alter_videojob_input_videofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiosetting',
            name='own_words',
            field=models.TextField(blank=True, help_text='Comma separated string of words'),
        ),
        migrations.AlterField(
            model_name='videojob',
            name='input_videofile',
            field=models.FileField(upload_to=videojobs.models.get_input_videofile_path),
        ),
    ]
