# Generated by Django 5.0.8 on 2024-08-10 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videojobs', '0005_alter_audiosetting_own_words'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiosetting',
            name='string',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
