# Generated by Django 5.0.8 on 2024-08-09 11:50

from django.db import migrations, models

import videojobs.models


class Migration(migrations.Migration):

    dependencies = [
        ('videojobs', '0005_alter_audiosetting_own_words_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videojob',
            name='input_videofile',
            field=models.FileField(upload_to=videojobs.models.get_input_videofile_path, validators=[videojobs.models.validate_input_file_extension]),
        ),
    ]
