# Generated by Django 5.0.8 on 2024-08-14 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videojobs', '0005_alter_videojob_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videojob',
            name='status',
            field=models.CharField(blank=True, choices=[('P', 'Processing'), ('C', 'Completed'), ('F', 'Failed')], default='P', max_length=1),
        ),
    ]
