# Generated by Django 5.0.8 on 2024-08-16 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videojobs', '0006_alter_videojob_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audiosetting',
            old_name='xenophobia',
            new_name='insult',
        ),
    ]
