# Generated by Django 5.0.8 on 2024-08-10 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videojobs', '0007_alter_audiosetting_string'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audiosetting',
            name='string',
        ),
    ]
