# Generated by Django 5.0.8 on 2024-08-16 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videojobs', '0007_rename_xenophobia_audiosetting_insult'),
    ]

    operations = [
        migrations.AddField(
            model_name='videojob',
            name='error_message',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
