# Generated by Django 5.0.8 on 2024-08-18 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videojobs', '0009_alter_videojob_error_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videojob',
            name='audio_setting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='videojobs.audiosetting'),
        ),
        migrations.AlterField(
            model_name='videojob',
            name='video_setting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='videojobs.videosetting'),
        ),
    ]
