# Generated by Django 5.0.8 on 2024-08-18 12:32

import videojobs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videojobs', '0010_alter_videojob_audio_setting_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videojob',
            name='input_video',
            field=models.FileField(upload_to=videojobs.models.get_input_video_path, validators=[videojobs.models.validate_input_video_size]),
        ),
    ]
