# Generated by Django 5.0.8 on 2024-08-24 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videojobs', '0012_alter_videojob_input_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiosetting',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='videojob',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='videosetting',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
