# Generated by Django 5.0.8 on 2024-09-03 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videojobs', '0013_audiosetting_updated_at_videojob_updated_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videosetting',
            old_name='bad_habits',
            new_name='gore',
        ),
        migrations.RenameField(
            model_name='videosetting',
            old_name='blood',
            new_name='smoking',
        ),
        migrations.RemoveField(
            model_name='videosetting',
            name='nudity',
        ),
        migrations.AlterField(
            model_name='videojob',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('ru', 'Russian')], max_length=2),
        ),
    ]
