# Generated by Django 5.0.9 on 2024-09-13 14:37

from django.db import migrations, models

import videojobs.models


class Migration(migrations.Migration):

    dependencies = [
        ('videojobs', '0014_rename_bad_habits_videosetting_gore_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videojob',
            name='output_video',
            field=models.FileField(blank=True, null=True, upload_to=videojobs.models.get_output_video_path),
        ),
    ]
