# Generated by Django 5.0.8 on 2024-08-21 15:57

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_alter_subplan_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='start_date',
            field=models.DateField(blank=True, default=datetime.date(2024, 8, 21)),
        ),
    ]
