# Generated by Django 5.0.8 on 2024-08-21 19:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0007_alter_subscription_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='subplan',
            name='yearly_discount',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='subplan',
            name='duration_months',
            field=models.IntegerField(choices=[(1, '1 month'), (12, '12 months')]),
        ),
    ]
